variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/
    - .m2/repository
    - download/
    - Gradle/

stages:
  - build
  - test

windows_job:
  #  image:  mcr.microsoft.com/windows/servercore:20H2
  stage: test
  tags:
    - windows
  variables:
    ErrorActionPreference: STOP
  script:
    - 'if(-Not (Test-Path .\download)) {New-Item -ItemType Directory -Force -Path .\download}'
    - 'if(-Not (Test-Path .\download\jdk11.zip)) {Invoke-WebRequest -UseBasicParsing -Uri "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip" -OutFile .\download\jdk11.zip}'
    - 'Expand-Archive -Path ".\download\jdk11.zip" -DestinationPath "C:\JDK11"'
    - '$env:JAVA_HOME="C:\JDK11\jdk-11.0.11+9"'
    - 'if(-Not (Test-Path .\download\gradle-6.8.3-bin.zip)) {Invoke-WebRequest -UseBasicParsing -Uri "https://services.gradle.org/distributions/gradle-6.8.3-bin.zip" -OutFile .\download\gradle-6.8.3-bin.zip}'
    - 'if(-Not (Test-Path .\Gradle)) {Expand-Archive -Path ".\download\gradle-6.8.3-bin.zip" -DestinationPath ".\Gradle"}'
    - 'cmd /c .\Gradle\gradle-6.8.3\bin\gradle clean test -i'
    - 'exit /b %errorlevel%'

macos_job:
  image: gradle:6.5-jdk11
  stage: test
  tags:
    - macos
  script:
    - 'gradle clean test -i'

ubuntu_job:
  image: gradle:6.5-jdk11
  stage: test
  tags:
    - ubuntu
  script:
    - 'gradle clean test -i'
