variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

#cache:
#  paths:
#    - venv/
#    - .m2/repository
#    - download/
#    - Gradle/

stages:
  - build
  - test

windows_job:
  #  image:  mcr.microsoft.com/windows/servercore:20H2
  stage: test
  tags:
    - windows
  variables:
    ErrorActionPreference: STOP
  script:
    - if(-Not (Test-Path .\download)) {New-Item -ItemType Directory -Force -Path .\download}
    - if(-Not (Test-Path .\download\jdk11.zip)) {Invoke-WebRequest -UseBasicParsing -Uri "https://github.com/AdoptOpenJDK/openjdk11-binaries/releases/download/jdk-11.0.11%2B9/OpenJDK11U-jdk_x64_windows_hotspot_11.0.11_9.zip" -OutFile .\download\jdk11.zip}
    - Expand-Archive -Path ".\download\jdk11.zip" -DestinationPath "C:\JDK11"
    - $env:JAVA_HOME="C:\JDK11\jdk-11.0.11+9"
    - if(-Not (Test-Path .\download\gradle-6.8.3-bin.zip)) {Invoke-WebRequest -UseBasicParsing -Uri "https://services.gradle.org/distributions/gradle-6.8.3-bin.zip" -OutFile .\download\gradle-6.8.3-bin.zip}
    - if(-Not (Test-Path .\Gradle)) {Expand-Archive -Path ".\download\gradle-6.8.3-bin.zip" -DestinationPath ".\Gradle"}
    - $cmnd = powershell.exe -command {.\Gradle\gradle-6.8.3\bin\gradle clean test 2>&1 | Write-Host; exit(0)}
    - if ("Success" -in $cmnd[-2..-1]) {exit(0)} else {exit(1)}

macos_job:
  stage: test
  tags:
    - macos
    - shell
  script:
    - echo "$(uname)"
    - sw_vers
    - tmpdir=$(mktemp -d /tmp/album-app-test.XXXXXX)
    - echo $tmpdir
    - echo $tmpdir > /tmp/tmpdir
    - curl https://repo.anaconda.com/miniconda/Miniconda3-latest-MacOSX-x86_64.sh --output $tmpdir/miniconda.sh
    - bash $tmpdir/miniconda.sh -b -p $tmpdir/miniconda
    - export PATH=$PATH:$tmpdir/miniconda/bin/
    - echo $PATH
    - conda create --name album-app
    - source $tmpdir/miniconda/bin/activate
    - conda activate album-app
    - conda install openjdk=11.0.6
    - curl -k -L -v -X GET https://services.gradle.org/distributions/gradle-6.8.3-bin.zip > $tmpdir/gradle-6.8.3-bin.zip
    - unzip -d $tmpdir/gradle $tmpdir/gradle-6.8.3-bin.zip
    - ls $tmpdir/gradle/gradle-6.8.3
    - $tmpdir/gradle/gradle-6.8.3/bin/gradle clean test

ubuntu_job:
  image: gradle:6.5-jdk11
  stage: test
#  tags:
#    - ubuntu
  script:
    - 'gradle clean test'
